### ISSUE TITLE
Class twig.string does not exist

### ISSUE THREAD

**Issue by rajakhoury** [alxy/oc-cashier-plugin#2]
This error occurs in the InvoiceTemplate Model. Any Idea ? Thanks for this plugin!

    <?php namespace RajaKhoury\Cashier\Models;
        
        use App;
        use File;
        use Model;
        use October\Rain\Mail\MailParser;
        use October\Rain\Parse\Syntax\SyntaxModelTrait;
        use October\Rain\Parse\Syntax\Parser;
        
        
        /**
         * InvoiceStatus Model
         */
        class InvoiceTemplate extends Model
        {
        
            use SyntaxModelTrait;
        
            /**
             * @var string The database table used by the model.
             */
            public $table = 'cashier_invoice_templates';
            /**
             * @var array Guarded fields
             */
            protected $guarded = [];
            /**
             * @var array Fillable fields
             */
            protected $fillable = [];
            /**
             * @var array List of attribute names which are json encoded and decoded from the database.
             */
            protected $jsonable = ['syntax_data', 'syntax_fields'];
            public $timestamps = false;
            public function getContentCssAttribute($content)
            {
                if (!$this->exists || !strlen($content))
                    return File::get(__DIR__ . '/invoicetemplate/default_content.css');
                return $content;
            }
            public function getContentHtmlAttribute($content)
            {
                if (!$this->exists || !strlen($content))
                    return File::get(__DIR__ . '/invoicetemplate/default_content.htm');
                return $content;
            }
            public function beforeSave()
            {
                $this->makeSyntaxFields($this->content_html);
            }
            public function renderInvoice($invoice)
            {
                $twig = App::make('twig.string');
                $parser = $this->getSyntaxParser($this->content_html);
                $invoiceData = $this->getSyntaxData();
                $invoiceTemplate = $parser->render($invoiceData);
                $twigData = [
                    'invoice' => $invoice,
                    'css' => $this->content_css
                ];
                $twigTemplate = $twig->render($invoiceTemplate, $twigData);
                return $twigTemplate;
            }
        }

**Comment by alxy** [comment]
Yes, the old IoC binding is deprecated. You should adjust the method to look like this: https://github.com/responsiv/pay-plugin/blob/master/models/InvoiceTemplate.php#L57-L70

However, this plugin hasnt been maintained for over a year now and has never been in a usable state. So feel free to use it, but be advised that it was never meant to be used in production.

**Comment by vojtasvoboda** [comment]
I have sent #3 pull request

**Comment by rajakhoury** [comment]
@alxy I understand. I end up using the Stripe API not cashier but your plugin was very helpful to get started and learning how to implement a model behavior. Thank you Alxy

Just a request : It would be great to have such plugin for October :))

**Comment by alxy** [comment]
No problem, you can use mine as a base and release one to the October marketplace ☺️
